function [ tempF, tempB] = Nmgsd(VgDC,VgAC,AttnG,VsdAC,AttnS,il)
%UNTITLED9 Summary of this function goes here
%   Detailed explanation goes here
if nargin == 6
    tempF = [num2str(VgDC,'%2.2f'),'V_VgDC_',...
        num2str(VgAC,'%8.2f'),'mV_-',...
        num2str(AttnG,'%02.f'),'dB_VgAC_',...
        num2str(VsdAC,'%8.2f'),'mV_-',...
        num2str(AttnS,'%02.f'),'dB_VsdAC_Loop_',...
        num2str(il),'_FWD.txt'];
    tempB = [num2str(VgDC,'%2.2f'),'V_VgDC_',...
        num2str(VgAC,'%8.2f'),'mV_-',...
        num2str(AttnG,'%02.f'),'dB_VgAC_',...
        num2str(VsdAC,'%8.2f'),'mV_-',...
        num2str(AttnS,'%2.f'),'dB_VsdAC_Loop_',...
        num2str(il),'_BKW.txt'];
elseif nargin ==5
    tempF = [num2str(VgDC,'%2.2f'),'V_VgDC_',...
        num2str(VgAC,'%8.2f'),'mV_-',...
        num2str(AttnG,'%02.f'),'dB_VgAC_',...
        num2str(VsdAC,'%8.2f'),'mV_-',...
        num2str(AttnS,'%02.f'),'dB_VsdAC__FWD.txt'];
    tempB = [num2str(VgDC,'%2.2f'),'V_VgDC_',...
        num2str(VgAC,'%8.2f'),'mV_-',...
        num2str(AttnG,'%02.f'),'dB_VgAC_',...
        num2str(VsdAC,'%8.2f'),'mV_-',...
        num2str(AttnS,'%2.f'),'dB_VsdAC__BKW.txt'];
end
end

